import React, { useEffect, useState } from "react";
import "../styles/conduta.css";

function Conduta() {
    return (
        <div>
           <div class="title-conduta"> 
               <h2>Código de conduta</h2>
            </div> 
             <div class="subtitle-conduta"> 
                Por favor, leia com atenção o Código de Conduta.
                <br />Ao se cadastrar como Profissional Parceiro(a) na <span style={{color:"rgb(237,125,49)"}}>onservicebr.com</span>, você <span style={{color:"rgb(237,125,49)"}}>ESTÁ DE ACORDO COM O CÓDIGO DE CONDUTA</span>.
                <br />A recusa deste Código de Conduta do Website impedirá que você seja divulgado pelo nosso Website. 
                <br /> <br />
            </div>
            <div class="paragrafos-conduta">
                <p>&emsp;&emsp;Ao assinar eletronicamente o presente documento ou clicar em “Eu aceito” durante o cadastro como Profissional Parceiro, o(a) Usuário(a) atesta que:
                    <br />&emsp;&emsp;i.&emsp;&emsp;&nbsp;&nbsp;Leu e compreendeu todos os campos abaixo;
                    <br />&emsp;&emsp;ii.&emsp;&emsp;&nbsp;Lhe foi dada a oportunidade de, se necessário, consultar terceiros, como um advogado, para aconselhamento ou esclarecimento dos presentes termos;
                    <br />&emsp;&emsp;iii.&emsp;&emsp;Está judicialmente capaz de concordar e cumprir com todos os termos deste documento.</p>
                <p>&emsp;&emsp;As diretrizes abaixo apresentam condutas e circunstâncias que podem ocasionar sanções, incluindo a perda de acesso à plataforma da OnService. Recomendamos uma leitura completa deste documento. Sempre haverá eventos imprevistos que também poderão levar à aplicação de sanções, de modo que tais diretrizes serão atualizadas frequentemente.</p>
                <p>&emsp;&emsp;No presente documento, o termo “<span style={{color:"rgb(237,125,49)"}}>Profissional Parceiro</span>” refere-se a pessoa que divulga seu contato e seu trabalho, denominado como “<span style={{color:"rgb(237,125,49)"}}>Serviço</span>”, na plataforma da OnService. “<span style={{color:"rgb(237,125,49)"}}>Contratante</span>” é uma pessoa cadastrada na plataforma que possui intuito de contratar um Serviços. “<span style={{color:"rgb(237,125,49)"}}>Usuário</span>” é o termo utilizado para referir-se à uma pessoa que usa a plataforma, seja para anunciar ou contratar um Serviços. O Código de Conduta é subdividido em “<span style={{color:"rgb(237,125,49)"}}>Cláusulas</span>”.</p>
                <p><br /><span style={{color:"rgb(237,125,49)",fontWeight:"bold"}}>1. INTRODUÇÃO E DISPOSIÇÕES GERAIS</span></p>
                <p>1.1. Bem-vindo à OnService! Este é o Código de Conduta, o qual rege o acesso e uso, dentro do Brasil, dos Serviços prestados através de aplicação tecnológica, sítios da Internet e conteúdos relacionados aos Profissionais Parceiros(as) para o exercício da profissão “<span style={{color:"rgb(237,125,49)"}}>prestador de serviços/autônomo/freelancer</span>” que decidam utilizar os Serviços da OnService, disponibilizados pela OnService Ltda. (“OnService”), inscrita no CNPJ/MF sob o nº 18.033.552/0001-61, com sede na Rua Sansão Alves dos Santos, nº 400, Bairro Cidade Monções, CEP 04571-090, Cidade e Estado de São Paulo, ou por qualquer de suas afiliadas. A OnService é proprietária da plataforma OnService e de todo o conteúdo hospedado sob o domínio <span style={{color:"rgb(237,125,49)"}}>onservicebr.com.</span> Todos os direitos reservados.</p>
                <div class="sub-clausulas-conduta">
                    <p>1.1.1. POR FAVOR, LEIA COM ATENÇÃO TODAS AS CLÁUSULAS ANTES DE ACESSAR OU USAR OS SERVIÇOS.</p>
                </div>
                <p>1.2. ACEITAÇÃO DO CÓDIGO DE CONDUTA. AO SE CADASTRAR E UTILIZAR CONTINUAMENTE OS SERVIÇOS, O(A) PROFISSIONAL PARCEIRO(A) DECLARARÁ TER LIDO, ENTENDIDO E ACEITO O CÓDIGO DE CONDUTA. CASO, A QUALQUER TEMPO, O(A) PROFISSIONAL PARCEIRO(A) NÃO CONCORDE COM OS AS CLÁUSULAS DO CÓDIGO DE CONDUTA, DEVERÁ CESSAR IMEDIATAMENTE A UTILIZAÇÃO DA PLATAFORMA DIGITAL DA ONSERVICE.</p>
                <div class="sub-clausulas-conduta">
                    <p>1.2.1. Cláusulas adicionais poderão se aplicar a determinados Serviços, tais como condições para categorias específicas, eventos, regulamentos, atividades, promoções em particular ou ações de recompensas, e essas Cláusulas adicionais serão divulgados em relação aos respectivos Serviços. As Cláusulas adicionais são complementares e considerados parte integrante destas Cláusulas para os efeitos dos respectivos Serviços. As Cláusulas adicionais prevalecerão sobre estas Cláusulas em caso de conflito somente com relação àquilo que forem específicos.</p>
                </div>    
                <p>1.3. Comunicação com o Profissional Parceiro. O Profissional Parceiro autoriza a OnService a enviar notificações administrativas no aplicativo, por e-mail, SMS, em uma publicação em seu site ou por qualquer outro meio de comunicação disponível com conteúdo de natureza informativa e promocional relacionado aos Serviços.</p>
                <p>1.4. Alteração das Cláusulas do Código de Conduta. A OnService reserva o direito de realizar alterações e atualizações nas Cláusulas do Código de Conduta, a qualquer momento, sem a necessidade de aviso prévio. Em caso de alterações de Cláusulas que restrinjam direitos dos Profissionais Parceiros, a OnService poderá comunicar tal alteração, ao seu critério, através dos meios de comunicação. Todavia, esta liberalidade não afasta a responsabilidade do Profissional Parceiro de verificar periodicamente o Código de Conduta. Caso o Profissional Parceiro não concorde com as alterações das Cláusulas, deverá cancelar sua conta e cessar toda e qualquer utilização dos Serviços. O fato de o Profissional Parceiro continuar a acessar ou usar os Serviços após essa postagem representa seu consentimento em vincular-se às Cláusulas alteradas.</p>
                <p><br /><span style={{color:"rgb(237,125,49)",fontWeight:"bold"}}>2. DADOS DO PROFISSIONAL PARCEIRO E PRIVACIDADE</span></p>
                <p>2.1. A ONSERVICE POSSUI UMA POLÍTICA EXPRESSA SOBRE PRIVACIDADE. AS INFORMAÇÕES DE REGISTRO E OUTRAS INFORMAÇÕES SOBRE O PROFISSIONAL PARCEIRO ESTÃO SUJEITAS AO TRATAMENTO REFERIDO EM TAL POLÍTICA DE PRIVACIDADE. O PROFISSIONAL PARCEIRO ENTENDE E CONCORDA QUE O SEU USO E A PRESTAÇÃO DO SERVIÇO ENVOLVEM A COLETA E UTILIZAÇÃO DE INFORMAÇÕES E DADOS SOBRE O PROFISSIONAL PARCEIRO (CONFORME DEFINIDO NA POLÍTICA DE PRIVACIDADE APLICÁVEL), INCLUINDO A TRANSFERÊNCIA DESTAS INFORMAÇÕES E DADOS PARA OUTROS TERRITÓRIOS, PARA FINS DE ARMAZENAMENTO, PROCESSAMENTO E UTILIZAÇÃO PELA ONSERVICE, SUA CONTROLADORA E DEMAIS EMPRESAS DO MESMO GRUPO ECONÔMICO, PARA ENVIO ÀS AUTORIDADES COMPETENTES PARA FINS DE REALIZAÇÃO DE CADASTRAMENTO DOS PROFISSIONAIS PARCEIROS, PARA AS FINALIDADES DA PRESTAÇÃO DO SERVIÇO E DEMAIS PREVISTAS NA POLÍTICA DE PRIVACIDADE. FAVOR CONSULTAR A POLÍTICA DE PRIVACIDADE DA ONSERVICE NO SEGUINTE LINK: <span style={{color:"rgb(237,125,49)"}}>https://onservicebr.com/politica_de_privacidade</span>. A POLÍTICA DE PRIVACIDADE DA ONSERVICE CONSTITUI PARTE INTEGRANTE DO CÓDIGO DE CONDUTA.</p>
                <p><br /><span style={{color:"rgb(237,125,49)",fontWeight:"bold"}}>3. CADASTRO</span></p>
                <p>3.1. Para divulgar seus Serviços, o Profissional Parceiro deve registrar-se e manter apenas uma conta pessoal de Profissional Parceiro. O Profissional Parceiro deve ter capacidade civil, possuir capacitação para realizar seu Serviços com excelência e deverá cumprir todos os requisitos legais correspondentes ao local de sua atuação para exercício da atividade de prestação de Serviços autônoma. O Profissional Parceiro que desejar utilizar o Serviço deverá obrigatoriamente preencher os campos de cadastro exigidos e responderá pela veracidade das informações declaradas, obrigando-se a manter informações válidas, atualizadas e corretas. Em caso de não confirmação de seus dados, o acesso do Profissional Parceiro ao Serviço poderá ser bloqueado, a exclusivo critério da OnService.</p>
                <p>3.2. Após receber os dados de cadastro, a OnService efetuará uma análise e poderá aceitar ou recusar a solicitação de cadastro do Profissional Parceiro. A OnService também poderá realizar a checagem de antecedentes criminais e quaisquer outras verificações que considerar oportunas ou que sejam exigidas pela legislação aplicável.</p>
                <p>3.3. O perfil do Profissional Parceiro é exclusivo e intransferível. O Profissional Parceiro compromete-se, mediante aceitação das Cláusulas do Código de Conduta, a não compartilhar sua conta com terceiros, sendo vedada a transferência de sua conta, sob pena de cancelamento imediato da conta do Profissional Parceiro, além de encaminhamento do caso às autoridades públicas para análise de eventuais penalidades criminais e civis aplicáveis.</p>
                <div class="sub-clausulas-conduta">
                    <p>3.3.1. A OnService se reserva o direito de solicitar documentos adicionais para confirmação de cadastros, bem como outros métodos de identificação e autenticação do Profissional Parceiro, por ocasião do cadastro e enquanto o Profissional Parceiro utilizar os Serviços a qualquer tempo. Mesmo após a confirmação do cadastro, é possível o cancelamento da conta caso sejam verificadas incongruências no processo de verificação, a exclusivo critério da OnService.</p>
                </div>
                <div class="sub-clausulas-conduta">
                    <p>3.3.2. As informações da conta são de exclusiva responsabilidade de quem as inseriu. No caso de acarretarem danos ou prejuízos de qualquer espécie, as medidas cabíveis podem ser tomadas pela OnService a fim de resguardar seus interesses e a integridade dos clientes, demais Profissionais Parceiros do aplicativo e da própria OnService.</p>
                </div>
                <p>3.4. O Profissional Parceiro se compromete, sob as penas da lei, a utilizar sua conta da plataforma apenas de maneira e para fins estritamente legais, legítimos e permitidos por estas Cláusulas.</p>
                <p>3.5. Mudanças nos dados de cadastro são permitidas. Porém, para mudanças de nome, CPF ou foto de perfil, a OnService efetuará uma análise e, após o período de verificação e validação, poderá aceitar ou recusar a solicitação de mudança nos dados cadastro do Profissional Parceiro.</p>
                <p><br /><span style={{color:"rgb(237,125,49)",fontWeight:"bold"}}>4. SERVIÇOS</span></p>
                <p>4.1. Serviços prestados pela OnService. Os Serviços consistem vitrine digital para Profissionais Parceiros promoverem sua imagem e trabalho, mediante licenciamento e uso de software, em que a OnService é a licenciante da plataforma de forma não-exclusiva, que possibilita ao Contratante localizar e contatar Profissionais Parceiros interessados em realizar o Serviços que o Contratante tem interesse.</p>
                <div class="sub-clausulas-conduta">
                    <p>4.1.1. O Profissional Parceiro concede à OnService as autorizações necessárias para a correta execução do Serviços, nomeando-a sua representante para que, em caso de algum eventual problema, nossa equipe tente ajudar na medida do possível para solucionar todas as adversidades.</p>
                </div>
                <p>4.2. A OnService concede ao Profissional Parceiro uma licença limitada, pessoal, não exclusiva, não transferível, não comercial e plenamente revogável, para utilizar a Plataforma em seu smartphone, tablet ou computador em conformidade com as condições previstas nestas Cláusulas.</p>
                <p>4.3. A OnService não se responsabiliza por quaisquer danos sofridos pelo Profissional Parceiro em razão de cópia, transferência, distribuição ou qualquer outra forma de utilização de conteúdo protegido disponibilizado na plataforma.</p>
                <p>4.4. A OnService reserva a si todos os direitos à plataforma não expressamente concedidos aqui.</p>
                <div class="sub-clausulas-conduta">
                    <p>4.4.1. Através da plataforma, o Profissional Parceiro receberá, por meio do WhatsApp, contatos de possíveis oportunidades de realização de Serviços, de acordo com a categoria selecionada pelo Contratante, localização e destino, opcionais e outros critérios presentes ou futuros que venham a ser determinados pela OnService.</p>
                </div>
                <p>4.5. A OnService poderá prestar outros Serviços ou oferecer produtos vinculados ou não ao Serviço, gratuitos ou onerosos, ao seu critério. Tais produtos, Serviços e entregas estão sujeitos às presentes Cláusulas e definidos como Serviço para todos os efeitos legais deste Código de Conduta.</p>
                <p>4.6. O Serviço não deve ser utilizado para qualquer finalidade que não as expressamente autorizadas por estas Cláusulas.</p>
                <p>4.7. Pagamento pelos Serviços. A OnService é uma plataforma gratuita, de modo que 100% do valor do Serviços prestado será adimplido diretamente ao Profissional Parceiro, sem a cobrança de taxas adicionais. Como remuneração pela Intermediação entre Contratantes e Profissionais Parceiros, a OnService não cobrará do Profissional Parceiro um valor por cada Serviços prestado. Apesar de não possuir nenhuma cobrança fixa, a OnService oferece pacotes de planos para uma maior visibilidade em nossa plataforma, que podem ser consultados em <span style={{color:"rgb(237,125,49)"}}>www.onservicebr.com/assinatura_premium</span>.</p>
                <p><br /><span style={{color:"rgb(237,125,49)",fontWeight:"bold"}}>5. RESPONSABILIDADES</span></p>
                <p>5.1. A OnService não se responsabiliza por nenhum tipo de transação financeira entre Contratantes e Profissionais Parceiros, podendo oferecer, ou não, algum tipo de suporte e auxílio para que o próprio Contratante ou Profissional Parceiro que se sentir lesado procure as medidas cabíveis legalmente.</p>
                <p>5.2. A OnService não se responsabiliza pela qualidade do Serviços prestado, sendo de responsabilidade única e exclusiva do Profissional Parceiro apresentar um bom trabalho. A OnService tem o direito de oferecer ajuda, ou não, para que o Contratante que se sentir lesado possa procurar seus direitos legais.</p>
                <p>5.3. INEXISTÊNCIA DE RELAÇÃO DE TRABALHO, VÍNCULO DE EMPREGO E OUTROS. NÃO SE ESTABELECE ENTRE O PROFISSIONAL PARCEIRO E A ONSERVICE QUALQUER VÍNCULO DE NATUREZA SOCIETÁRIA, EMPREGATÍCIA E/OU ECONÔMICA, SENDO CERTO QUE O PROFISSIONAL PARCEIRO É LIVRE PARA REALIZAR SERVIÇOS QUANDO QUISER, BEM COMO PARA CESSAR A UTILIZAÇÃO DA PLATAFORMA A QUALQUER MOMENTO, AO SEU LIVRE E EXCLUSIVO CRITÉRIO. A ONSERVICE NÃO POSSUI UMA EQUIPE DE PROFISSIONAIS PARCEIROS CONTRATADOS, PRESTANDO EXCLUSIVAMENTE OS SERVIÇOS DE VITRINE E PROMOÇÃO VOLTADOS À FACILITAÇÃO DA CONTRATAÇÃO DE SERVIÇOS VARIADOS PERANTE UM PROFISSIONAL PARCEIRO CADASTRADO NA PLATAFORMA.</p>
                <p>5.4. RESPONSABILIDADES PELOS SERVIÇOS. A OnService não assume a responsabilidade por nenhum problema técnico no decorrer da execução do Serviços solicitado, nem se responsabiliza pela qualidade do Serviços, que fica a critério do Contratante avaliar o Profissional Parceiro pela nota em seu perfil. A OnService deverá ainda manter o bom funcionamento da plataforma na maior medida possível e disponibilizar canais de atendimento para ajudar a solucionar dúvidas e problemas dos usuários da plataforma.</p>
                <p>5.5. RESPONSABILIDADE PELOS SERVIÇOS PRESTADOS. A CONTRATAÇÃO DOS SERVIÇOS DE VARIADOS É FEITA DIRETAMENTE ENTRE OS CLIENTES E OS PROFISSIONAIS PARCEIROS. A ONSERVICE NÃO SE RESPONSABILIZA POR QUAISQUER PERDAS, PREJUÍZOS OU DANOS DE QUALQUER NATUREZA QUE SEJAM DECORRENTES DA RELAÇÃO ENTRE CLIENTE E PROFISSIONAL PARCEIRO. O PROFISSIONAL PARCEIRO ENTENDE E CONCORDA QUE A ONSERVICE NÃO SERÁ RESPONSÁVEL POR QUAISQUER DANOS OU PREJUÍZOS QUE VENHAM A SER CAUSADOS POR UM CLIENTE AO RESPECTIVO PROFISSIONAL PARCEIRO. O CONTRATANTE ENTENDE E CONCORDA QUE A ONSERVICE NÃO SERÁ RESPONSÁVEL POR QUAISQUER DANOS OU PREJUÍZOS QUE VENHAM A SER CAUSADOS POR UM PROFISSIONAL PARCEIRO AO RESPECTIVO CONTRATANTE.</p>
                <div class="sub-clausulas-conduta">
                    <p>5.5.1. Danos e prejuízos causados pelos Profissionais Parceiros. O Profissional Parceiro será responsável por quaisquer danos ou prejuízos que causar ao(s) Contratante(s) e concorda em indenizar e manter a OnService indene em relação a quaisquer demandas, perdas, prejuízos ou danos direta ou indiretamente relacionados a atos ou fatos causados pelo Profissional Parceiro. O Profissional Parceiro é o único e exclusivo responsável por todos e quaisquer problemas relativos ao Serviço que prestar, bem como por quaisquer condutas indevidas ou ilegais que pratique.</p>
                </div>
                <p>5.6. Modificação ou encerramento do Serviço. A OnService se reserva o direito de, a qualquer tempo, modificar ou descontinuar, temporariamente ou permanentemente, o Serviço ou parte dele, com ou sem notificação. O Profissional Parceiro concorda que a OnService não será responsabilizada, nem terá qualquer obrigação adicional, implícita ou explícita, para com o Profissional Parceiro ou terceiros em razão de qualquer modificação, suspensão ou desativação do Serviço.</p>
                <p>5.7. Obrigação do Profissional Parceiro. O Profissional Parceiro deve respeitar todas as regras destas Cláusulas do Código de Conduta e de toda legislação aplicável. O descumprimento do Código de Conduta ou da legislação aplicável pelo Profissional Parceiro poderá resultar, a livre e exclusivo critério da OnService, o impedimento do seu acesso à plataforma. Mediante aceitação das Cláusulas do Código de Conduta, o Profissional Parceiro compromete-se a:</p>
                <p>       &emsp;&emsp;i.&emsp;&emsp;&nbsp;&nbsp;Realizar um Serviços de qualidade;
                    <br />&emsp;&emsp;ii.&emsp;&emsp;&nbsp;Agir perante a OnService e aos Contratantes com boa-fé, diligência, profissionalismo e respeito;
                    <br />&emsp;&emsp;iii.&emsp;&emsp;Obedecer a todas as exigências legais e regulatórias referentes aos Serviços prestados, incluindo as leis, regulamentos e demais normas aplicáveis em âmbito federal, estadual e municipal, em relação ao Profissional Parceiro.
                    <br />&emsp;&emsp;iv.&emsp;&emsp;&nbsp;Não discriminar ou selecionar, por nenhum motivo, os Contratantes;
                    <br />&emsp;&emsp;v.&emsp;&emsp;&nbsp;Responsabilizar-se integralmente pela prestação do Serviços;
                    <br />&emsp;&emsp;vi.&emsp;&emsp;Responsabilizar-se pelo uso de suas próprias ferramentas de trabalho.</p>
                    <p>5.8. Pagamento pelo Serviço. O pagamento do Serviços prestado é feito diretamente pelo(s) Contratante(s) ao Profissional Parceiro, a combinar diretamente entre si. O Profissional Parceiro pode optar por receber pagamentos da forma que bem entender, sendo obrigatória a estipulação prévia por E-Mail, SMS, WhatsApp ou outra forma escrita, a fim de proteger a integridade financeira de ambas as partes. </p>
                    <p>&emsp;&emsp;5.8.1. Preço do Serviço. O valor a ser pago pelo Contratante ao Profissional Parceiro deve ser informado por e-mail, SMS, WhatsApp ou outra forma escrita, antes da realização do Serviços, para que fique registrado e não haja nenhum tipo de divergência entre ambas as partes.</p>
                    <p>&emsp;&emsp;5.8.2. A OnService não se responsabiliza por pagamentos acordados única e exclusivamente pessoalmente, sendo de total risco e responsabilidade dos Usuários.</p>
                    <p>&emsp;&emsp;5.8.3. A OnService não se responsabiliza pela indenização ou ressarcimento do valor atribuído ao Serviço. Porém, serão analisadas denúncias com provas escritas enviadas à OnService de incongruência da forma ou valor entre o pagamento acordado de forma escrita e o pagamento exigido pessoalmente. Caso a denúncia seja considerada válida, a OnService, à sua livre discrição, poderá suspender ou banir a conta do Usuário acusado de uso inadequado ou abusivo da plataforma.</p>
                    <p></p>
            </div>
        </div>
    );



}
export default Conduta;