const Counter = [
    { jobCounted: "Analista de Sistemas", counter: "0" },
    { jobCounted: "Animador(a) de Festas", counter: "2" },
    { jobCounted: "Artesã(o)", counter: "1" },
    { jobCounted: "Assistente Técnico(a)", counter: "1" },
    { jobCounted: "Babá", counter: "1" },
    { jobCounted: "Barbeiro(a)", counter: "1" },
    { jobCounted: "Bartender", counter: "1" },
    { jobCounted: "Cabeleireiro(a)", counter: "2" },
    { jobCounted: "Coach", counter: "1" },
    { jobCounted: "Consultor(a) de Marketing Digital", counter: "1" },
    { jobCounted: "Depilador(a)", counter: "1" },
    { jobCounted: "Desenhista", counter: "0" },
    { jobCounted: "Designer Gráfico", counter: "1" },
    { jobCounted: "Diarista", counter: "1" },
    { jobCounted: "Editor(a) de Vídeos", counter: "1" },
    { jobCounted: "Eletricista", counter: "1" },
    { jobCounted: "Encanador(a)", counter: "1" },
    { jobCounted: "Especialista em Mídias", counter: "0" },
    { jobCounted: "Esteticista", counter: "1" },
    { jobCounted: "Faz Tudo", counter: "1" },
    { jobCounted: "Fisioterapeuta", counter: "2" },
    { jobCounted: "Fotógrafo(a)", counter: "1" },
    { jobCounted: "Fretes e Mudanças", counter: "1" },
    { jobCounted: "Garçom(Garçonete)", counter: "2" },
    { jobCounted: "Jardineiro(a)", counter: "0" },
    { jobCounted: "Manicure", counter: "2" },
    { jobCounted: "Manutenção de PABX", counter: "1" },
    { jobCounted: "Maquiador(a)", counter: "0" },
    { jobCounted: "Marceneiro(a)", counter: "1" },
    { jobCounted: "Micropigmentador(a)", counter: "1" },
    { jobCounted: "Montador(a) de Móveis", counter: "0" },
    { jobCounted: "Motoboy", counter: "2" },
    { jobCounted: "Motorista Particular", counter: "0" },
    { jobCounted: "Músico(a)", counter: "1" },
    { jobCounted: "Organizador(a) de Eventos", counter: "1" },
    { jobCounted: "Passeador(a) de Cães", counter: "1" },
    { jobCounted: "Personal Trainer", counter: "2" },
    { jobCounted: "Pintor(a)", counter: "2" },
    { jobCounted: "Professor(a) de Educação Física", counter: "1" },
    { jobCounted: "Professor(a) de Francês", counter: "0" },
    { jobCounted: "Professor(a) de Inglês", counter: "1" },
    { jobCounted: "Professor(a) de Programação", counter: "1" },
    { jobCounted: "Programador(a)", counter: "2" },
    { jobCounted: "Psicólogo(a)", counter: "3" },
    { jobCounted: "Publicitário(a)", counter: "1" },
    { jobCounted: "Recepcionista", counter: "1" },
    { jobCounted: "Terapeuta Ocupacional", counter: "0" },
    { jobCounted: "Tradutor(a)", counter: "1" },
    { jobCounted: "Vendedor(a)", counter: "1" },
]

export default Counter