const Database = [
    // { id: "1", jobsRight:["Cabeleireiro(a)", "Barbeiro(a)"], jobs: ["cabeleireiro(a)", "barbeiro(a)"], gender: "masculino", name: "Pablo Picasso", phone: "5516996758765", link: "/contrate/beleza/barbeiro(a)/1", picture: "../../../assets/profissionais/pablopicasso.png", description: "Por conseguinte, o surgimento do comércio virtual aponta para a melhoria das condições financeiras e administrativas exigidas. O incentivo ao avanço tecnológico, assim como a complexidade dos estudos efetuados deve passar por modificações independentemente do sistema de formação de quadros que corresponde às necessidades. A prática cotidiana prova que a revolução dos costumes exige a precisão e aaaaaaaaaaaaaaaaaaaaaa" },
    // { id: "2", jobsRight:["Barbeiro(a)"], jobs: ["barbeiro(a)"], gender: "masculino", name: "Vincent van Gogh", phone: "5516996758764", link: "/contrate/beleza/barbeiro(a)/2", picture: "../../../assets/profissionais/vincentvangogh.png", description: "Nunca é demais lembrar o peso e o significado destes problemas, uma vez que a valorização de fatores subjetivos agrega valor ao estabelecimento das regras de conduta normativas. Não obstante, o julgamento imparcial das eventualidades pode nos levar a considerar a reestruturação de alternativas às soluções ortodoxas. Do mesmo modo, a constante divulgação das informações representa uma abertura para a melhoria do remanejamento dos quadros" },
    // { id: "3", jobsRight:["Barbeiro(a)"], jobs: ["barbeiro(a)"], gender: "masculino", name: "Michelangelo", phone: "5516996758763", link: "/contrate/beleza/barbeiro(a)/3", picture: "../../../assets/profissionais/michelangelo.png", description: "Percebemos, cada vez mais, que a execução dos pontos do programa nos obriga à análise dos procedimentos normalmente adotados" },
    // { id: "4", jobsRight:["Barbeiro(a)"], jobs: ["barbeiro(a)"], gender: "masculino", name: "Salvador Dalí", phone: "5516996758761", link: "/contrate/beleza/barbeiro(a)/4", picture: "../../../assets/profissionais/salvadordali.png", description: "Todavia, a crescente influência da mídia possibilita uma melhor visão global das direções preferenciais no sentido do progresso. Por outro lado, o aumento do diálogo entre os diferentes setores produtivos assume importantes posições no estabelecimento do fluxo de informações. O cuidado em identificar pontos críticos no comprometimento entre as equipes auxilia a preparação e a composição das diretrizes de desenvolvimento para o futuro" },
    { id: "5", jobsRight:["Pintor(a)"], jobs: ["pintor(a)"], gender: "masculino", name: "Antônio Santos", phone: "5516981708327", link: "/contrate/manutencao/pintor(a)/5", picture: "../../../assets/profissionais/antoniosantos.jpg", description: "Pintor residencial com 25 anos de experiência em todas as atividades referentes à área de serviço." },
    { id: "6", jobsRight:["Assistente Técnico(a)"], jobs: ["assistente-tecnico(a)"], gender: "masculino", name: "Carlos Santana", phone: "5516993669115", link: "/contrate/tecnologia/assistente-tecnico(a)/6", picture: "../../../assets/profissionais/carlossantana.jpeg", description: "Técnico em informática. Faço manutenção em Notebooks, computadores, montagem de computadores, manutenção de rede de internet, e passo cabo de internet residencial." },
    { id: "7", jobsRight:["Psicólogo(a)"], jobs: ["psicologo(a)"], gender: "feminino", name: "Letícia Bareato", phone: "5516982704941", link: "/contrate/saude/psicologo(a)/7", picture: "../../../assets/profissionais/leticiabareato.jpg", description: "Psicóloga Comportamental, atua na área de Terapia Cognitivo-Comportamental, formada em 2013 pela UNESP - Bauru (SP). Psicoterapia à crianças, jovens e adultos. Orientação e reorientação profissional." },
    { id: "8", jobsRight:["Fisioterapeuta"], jobs: ["fisioterapeuta"], gender: "feminino", name: "Paula Ribeiro", phone: "5516994182004", link: "/contrate/saude/fisioterapeuta/8", picture: "../../../assets/profissionais/paularibeiro.jpg", description: "Fisioterapeuta com formação completa em Pilates. Atendimento online e individualizado. Ajudo pessoas que tem dor a melhorarem sua qualidade de vida, participação, produtividade e bem estar." },
    { id: "9", jobsRight:["Recepcionista", "Bartender", "Garcom(Garçonete)", "Passeador(a) de Cães"], jobs: ["recepcionista", "bartender", "garcom(garçonete)", "passeador(a)-de-caes"], gender: "feminino", name: "Laisa Massa", phone: "5517981492300", link: "/contrate/eventos/bartender/9", picture: "../../../assets/profissionais/laisamassa.png", description: "Sempre trabalhei em bares ou eventos de garçonete e servindo bebidas, também trabalhei em lanchonetes fazendo sucos, lanches etc... Acostumada a trabalhar em festas em períodos noturnos que viram a noite." },
    { id: "10", jobsRight:["Tradutor(a)"], jobs: ["tradutor(a)"], gender: "feminino", name: "Letícia Miguel", phone: "5516997008519", link: "/contrate/ensino/tradutor(a)/10", picture: "../../../assets/profissionais/leticiamiguel.png", description: "Tradutora com mais de quatro anos de experiência e prática com traduções acadêmicas." },
    { id: "11", jobsRight:["Professor(a) de Programação", "Programador(a)"], jobs: ["professor(a)-de-programacao", "programador(a)"], gender: "masculino", name: "Marcio Barros", phone: "5516981925092", link: "/contrate/tecnologia/programador(a)/11", picture: "../../../assets/profissionais/marciobarros.png", description: "Foco em desenvolvimento de aplicativos para controle de empresas." },
    { id: "12", jobsRight:["Encanador(a)", "Eletricista", "Faz Tudo"], jobs: ["encanador(a)", "eletricista", "faz-tudo"], gender: "masculino", name: "Reginaldo Pereira da Silva", phone: "5516996031666", link: "/contrate/manutencao/encanador(a)/12", picture: "../../../assets/profissionais/reginaldosilva.png", description: "Mais de 5 anos com experiência em Hidráulica (reparos e instalações) e Elétrica (reparos e instalações)." },
    { id: "13", jobsRight:["Psicólogo(a)"], jobs: ["psicologo(a)"], gender: "feminino", name: "Mariana Claudino", phone: "5517997664665", link: "/contrate/saude/psicologo(a)/13", picture: "../../../assets/profissionais/marianaclaudino.png", description: "Psicóloga, especialista em Psicologia da Saúde. Psicanalista em formação, atendo adolescentes e adultos." },
    { id: "14", jobsRight:["Psicólogo(a)"], jobs: ["psicologo(a)", "coach"], gender: "feminino", name: "Cristiane Bassi Raimundo", phone: "5516991788147", link: "/contrate/saude/psicologo(a)/14", picture: "../../../assets/profissionais/cristianeraimundo.png", description: "Psicóloga clínica com abordagem em TCC-Teoria Cognitivo Comportamental. Atendimentos individuais a adolescentes e adultos. Coaching de vida, executivo e de carreira.​" },
    { id: "15", jobsRight:["Motoboy"], jobs: ["motoboy"], gender: "masculino", name: "Rone Silva", phone: "5516994195353", link: "/contrate/outros/motoboy/15", picture: "../../../assets/profissionais/ronesilva.png", description: "Trabalho com coleta e entrega de produtos dentro de São Carlos-SP." },
    { id: "16", jobsRight:["cabeleireiro(a)"], jobs: ["cabeleireiro(a)"], gender: "feminino", name: "Raquel Tanaka", phone: "5516992411854", link: "/contrate/beleza/cabeleireiro(a)/16", picture: "../../../assets/profissionais/raqueltanaka.png", description: "Conhecida como Nani Cabeleireira, atendo homens, mulheres e crianças no domicílio do cliente, com todos os cuidados de higienização. Sou cabeleireira domiciliar há 9 anos, minha especialização é em atendimento domiciliar. Não cobro taxas de deslocamento." },
    { id: "17", jobsRight:["Artesã(o)"], jobs: ["artesa(o)"], gender: "feminino", name: "Ivone Turaça", phone: "5516991591350", link: "/contrate/outros/artesa(o)/17", picture: "../../../assets/profissionais/ivoneturaca.png", description: "Sabonete artesanal, exclusivo e personalizado, sabonete líquido, aromatizadores de ambientes, sachês, lembrancinha para batizado, casamento, aniversário e outras ocasiões." },
    { id: "18", jobsRight:["Professor(a) de Educação Física", "Personal Trainer"], jobs: ["professor(a)-de-educacao-fisica", "personal-trainer"], gender: "masculino", name: "Bruno Brabo", phone: "5516981548634", link: "/contrate/saude/personal-trainer/18", picture: "../../../assets/profissionais/brunobrabo.png", description: "Sou Personal Trainer, realizo atendimentos individualizados ou para pequenos grupos (2-3 pessoas). Treinamento funcional e assessoria esportiva para todas as idades." },
    { id: "19", jobsRight:["Fisioterapeuta", "Esteticista"], jobs: ["fisioterapeuta", "esteticista"], gender: "feminino", name: "Dalgiza Silva", phone: "5516996365090", link: "/contrate/saude/fisioterapeuta/19", picture: "../../../assets/profissionais/dalgizasilva.png", description: "Fisioterapeuta e esteticista, com especialização em tratamentos corporais e faciais como limpeza de pele, rejuvenescimento, gordura localizada, fototerapia, LED, Vacum Laserterapia, eletroestimulação, ultrassom, etc." },
    { id: "20", jobsRight:["Pintor(a)"], jobs: ["pintor(a)"], gender: "masculino", name: "Adilso Teixeira", phone: "5516997607554", link: "/contrate/manutencao/pintor(a)/20", picture: "../../../assets/profissionais/adilsoteixeira.png", description: "Pintura profissional, com 27 anos de experiência, atendendo São Carlos e região" },
    { id: "21", jobsRight:["Fretes e Mudanças"], jobs: ["fretes-e-mudancas"], gender: "masculino", name: "Leonardo Gonçalves", phone: "5516991030434", link: "/contrate/outros/fretes-e-mudancas/21", picture: "../../../assets/profissionais/leonardogoncalves.png", description: "Trabalho com carreto e mudanças, tendo 3 anos de experiência" },
    { id: "22", jobsRight:["Manutenção de PABX"], jobs: ["manutencao-de-pabx"], gender: "masculino", name: "Darlan Meletti", phone: "5519996810017", link: "/contrate/tecnologia/manutencao-de-pabx/22", picture: "../../../assets/profissionais/darlanmeletti.png", description: "Técnico em telecomunicações, com mais 27 anos de experiência na área. Atendo empresas, indústrias, hotéis, comércios em geral." },
    { id: "23", jobsRight:["Publicitário(a)", "Consultor(a) de Marketing Digital"], jobs: ["publicitario(a)", "consultor(a)-de-marketing-digital"], gender: "feminino", name: "Carolina Ávila", phone: "5562981127288", link: "/contrate/outros/publicitario(a)/23", picture: "../../../assets/profissionais/carolinaavila.png", description: "Publicitária com mais de 10 anos de experiência de mercado, dou consultoria de marketing para quem deseja gerenciar, por conta própria, sua conta no Instagram e outras redes sociais. Também posso gerenciar a sua conta para você." },
    { id: "24", jobsRight: ["Artesã(o)","Marceneiro(a)"], jobs: ["artesa(o)", "marceneiro(a)"], gender: "masculino", name: "Maurilio Elias", phone: "5516991502388", link: "/contrate/outros/artesa(o)/24", picture: "../../../assets/profissionais/maurilioelias.png", description: "Trabalho com madeira há mais de 10 anos, fazendo charretes em miniatura, bancos, mesas, miniaturas de caminhões, prateleiras e muito mais." },

]

export default Database